"""
Data models and structures for the DELM-Core framework.
"""
from typing import Optional, Any, List

from pydantic import BaseModel, Field

class Task(BaseModel):
    """
    Represents a single sub-task in the decentralized multi-agent system.
    """
    id : int = Field(..., description="Unique identifier for the task.")

    name : str = Field(..., description="The description or instruction of the task.")

    # default_factory=list means this is an empty list by default

    depends_on: List[int] = Field(
        default_factory=list,
        description="List of task IDs that must be completed before this task."
    )

    # Optional[str] -> initially the result is None; when an Agent does its work, the result will be the response string
    result: Optional[str] = Field(
        default=None,
        description="The final answer/output generated by the agent."
    )

class ContextUpdate(BaseModel):
    """
    Represents a verified claim or finding to be added to the Shared Context.
    """
    claim: str = Field(..., description="The verified fact or summary generated by an agent.")

    evidence: str = Field(..., description="The raw text or source data that supports this claim.")

    source_task_id: int = Field(..., description="The ID of the task that generated this update.")
